all:
	g++ src/* -o build/a.out -std=c++11 -I../../json/ -Iinclude/ -I../../include/Cryptography/ -I../../include/Exceptions/ -I../../include/Utilities/ -L../../build/ -lYggdrasil -lssl -lcrypto
	cp build/a.out ../bin/ygg
